### ISSUE TITLE
Command line args to run full_eval_lm.py

### ISSUE THREAD

**Issue by bhattg** [ketranm/fan_vs_rnn#2]
Hi, It would be great if you can provide the cmd line args to run full_eval_lm.py. 

Thanks!

**Comment by ketranm** [comment]
Hi,
It's been a long time since I used this code. If I remember correctly, you need to download the data first by running `download_data.sh` script. It will download and extract data to `data/agr_50_mostcommon_10K.tsv`
Then assuming that you have a trained model `model.pth`, you can run the evaluation with the following command

```
python full_eval_lm.py --checkpoint model.pth --input data/agr_50_mostcommon_10K.tsv --batch_size 32 --output result.pkl
```

**Comment by bhattg** [comment]
Thanks, let me see if this works! :D

**Comment by bhattg** [comment]
Thanks, it works. Can you also tell what was the exact set of hyperparameters on which the numbers are being reported in the paper corresponding to the LM and VP?
